// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/avlrecords/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Recupera todos los registros Avl con opciones de paginación y filtrado por FkCompany y FkCustomer si están presentes en el contexto.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AvlRecords"
                ],
                "summary": "Obtiene todos los registros Avl",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página para la paginación",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Tamaño de página para la paginación",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Placa del vehículo",
                        "name": "Plate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Imei del dispositivo",
                        "name": "Imei",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de inicio para filtrar los registros Avl",
                        "name": "fromDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin para filtrar los registros Avl",
                        "name": "toDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de registros Avl",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.AvlRecord"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/avlrecords/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene un historico por su ID específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AvlRecords"
                ],
                "summary": "Obtiene un historico específico",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Historico",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalles del vehículo",
                        "schema": {
                            "$ref": "#/definitions/swagger.AvlRecord"
                        }
                    },
                    "400": {
                        "description": "Error: ID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Error: Vehículo no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tours/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Recupera todos los puntos de registros Avl con opciones de paginación y filtrado por FkCompany y FkCustomer si están presentes en el contexto.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tours"
                ],
                "summary": "Obtiene todos los puntos de registros Avl",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página para la paginación",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Tamaño de página para la paginación",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Placa del vehículo",
                        "name": "Plate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Imei del dispositivo",
                        "name": "Imei",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de inicio para filtrar los registros Avl",
                        "name": "fromDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin para filtrar los registros Avl",
                        "name": "toDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de puntos de registros Avl",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.AvlRecordPoint"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tours/excel/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Recupera todos los puntos de registros Avl con opciones de paginación y filtrado por FkCompany y FkCustomer si están presentes en el contexto.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tours"
                ],
                "summary": "Obtiene todos los puntos de registros Avl",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página para la paginación",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Tamaño de página para la paginación",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Placa del vehículo",
                        "name": "Plate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Imei del dispositivo",
                        "name": "Imei",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de inicio para filtrar los registros Avl",
                        "name": "fromDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de fin para filtrar los registros Avl",
                        "name": "toDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de puntos de registros Avl",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.AvlRecordPoint"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tours/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene un historico por su ID específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tours"
                ],
                "summary": "Obtiene un historico específico",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Historico",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalles del vehículo",
                        "schema": {
                            "$ref": "#/definitions/swagger.AvlRecord"
                        }
                    },
                    "400": {
                        "description": "Error: ID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Error: Vehículo no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swagger.AvlRecord": {
            "type": "object",
            "properties": {
                "altitude": {
                    "type": "integer"
                },
                "angle": {
                    "type": "integer"
                },
                "company": {
                    "type": "string"
                },
                "customer": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "hdop": {
                    "type": "integer"
                },
                "id_company": {
                    "type": "integer"
                },
                "id_customer": {
                    "type": "integer"
                },
                "imei": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "pdop": {
                    "type": "integer"
                },
                "plate": {
                    "type": "string"
                },
                "properties": {
                    "type": "string"
                },
                "satellites": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "timeStampEvent": {
                    "type": "string"
                }
            }
        },
        "swagger.AvlRecordPoint": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "plate": {
                    "type": "string"
                },
                "timeStampEvent": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:60060",
	BasePath:         "/Vehicle",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
